#!/usr/bin/env bash
set -euo pipefail

# Simple OCI CLI wrapper for idempotent dry-run plans and basic reporting.
# Usage: scripts/oci-bootstrap.sh --compartment COMP --resources vcn,subnet --dry-run

TIMESTAMP=$(date -u +%Y%m%dT%H%M%SZ)
OUT_DIR="outputs/oci-bootstrap"
mkdir -p "$OUT_DIR"

DRY_RUN=true
COMPARTMENT=""
RESOURCES=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run) DRY_RUN=true; shift ;;
    --apply) DRY_RUN=false; shift ;;
    --compartment) COMPARTMENT="$2"; shift 2 ;;
    --resources) RESOURCES="$2"; shift 2 ;;
    --help) echo "Usage: $0 [--dry-run|--apply] --compartment OCID [--resources csv]"; exit 0 ;;
    *) echo "Unknown arg: $1"; exit 1 ;;
  esac
done

if [ -z "$COMPARTMENT" ]; then
  echo "Error: --compartment is required" >&2
  exit 2
fi

if ! command -v oci >/dev/null 2>&1; then
  echo "OCI CLI not found in PATH. Install it first." >&2
  exit 3
fi

REPORT="$OUT_DIR/plan-$TIMESTAMP.json"

echo "{\"timestamp\": \"$TIMESTAMP\", \"compartment\": \"$COMPARTMENT\", \"dry_run\": $DRY_RUN, \"resources\": [" > "$REPORT"

IFS=',' read -ra REQS <<< "$RESOURCES"
FIRST=true
for r in "${REQS[@]}"; do
  r=$(echo "$r" | xargs)
  [ -z "$r" ] && continue
  if [ "$r" = "vcn" ]; then
    COUNT=$(oci network vcn list --compartment-id "$COMPARTMENT" --query "data | length(@)" --raw-output 2>/dev/null || echo 0)
    if [ "$FIRST" = true ]; then FIRST=false; else echo "," >> "$REPORT"; fi
    echo "  {\"resource\": \"vcn\", \"existing\": $COUNT }" >> "$REPORT"
  elif [ "$r" = "compute" ]; then
    COUNT=$(oci compute instance list --compartment-id "$COMPARTMENT" --query "data | length(@)" --raw-output 2>/dev/null || echo 0)
    if [ "$FIRST" = true ]; then FIRST=false; else echo "," >> "$REPORT"; fi
    echo "  {\"resource\": \"compute\", \"existing\": $COUNT }" >> "$REPORT"
  elif [ "$r" = "vault" ]; then
    COUNT=$(oci vault vault list --compartment-id "$COMPARTMENT" --query "data | length(@)" --raw-output 2>/dev/null || echo 0)
    if [ "$FIRST" = true ]; then FIRST=false; else echo "," >> "$REPORT"; fi
    echo "  {\"resource\": \"vault\", \"existing\": $COUNT }" >> "$REPORT"
  else
    # generic discovery
    if [ "$FIRST" = true ]; then FIRST=false; else echo "," >> "$REPORT"; fi
    echo "  {\"resource\": \"$r\", \"note\": \"no-op discovery\" }" >> "$REPORT"
  fi
done

echo "], \"notes\": \"Generated by scripts/oci-bootstrap.sh\" }" >> "$REPORT"

echo "Plan written to $REPORT"

if [ "$DRY_RUN" = false ]; then
  echo "Apply requested. This script does NOT perform destructive applies automatically." >&2
  echo "Open a PR or run with operator approval to make changes." >&2
fi

exit 0
